
#ifndef TOKEN_KIND_CC
#define TOKEN_KIND_CC
#include <algorithm>
#include <vector>
#include <string>
#include <map>

namespace {
    enum TokenType {
        START_OF_RESERVED_KEYWORD,
        ACCESSIBLE,
        ADD,
        ALL,
        ALTER,
        ANALYZE,
        AND,
        AS,
        ASC,
        ASENSITIVE,
        BEFORE,
        BETWEEN,
        BIGINT,
        BINARY,
        BLOB,
        BOTH,
        BY,
        CALL,
        CASCADE,
        CASE,
        CHANGE,
        CHAR,
        CHARACTER,
        CHECK,
        COLLATE,
        COLUMN,
        CONDITION,
        CONSTRAINT,
        CONTINUE,
        CONVERT,
        CREATE,
        CROSS,
        CURRENT_DATE,
        CURRENT_TIME,
        CURRENT_TIMESTAMP,
        CURRENT_USER,
        CURSOR,
        DATABASE,
        DATABASES,
        DAY_HOUR,
        DAY_MICROSECOND,
        DAY_MINUTE,
        DAY_SECOND,
        DEC,
        DECIMAL,
        DECLARE,
        DEFAULT,
        DELAYED,
        DELETE,
        DESC,
        DESCRIBE,
        DETERMINISTIC,
        DISTINCT,
        DISTINCTROW,
        DIV,
        DOUBLE,
        DROP,
        DUAL,
        EACH,
        ELSE,
        ELSEIF,
        ENCLOSED,
        ESCAPED,
        EXISTS,
        EXIT,
        EXPLAIN,
        FALSE,
        FETCH,
        FLOAT,
        FLOAT4,
        FLOAT8,
        FOR,
        FORCE,
        FOREIGN,
        FROM,
        FULLTEXT,
        GENERATED,
        GET,
        GRANT,
        GROUP,
        HAVING,
        HIGH_PRIORITY,
        HOUR_MICROSECOND,
        HOUR_MINUTE,
        HOUR_SECOND,
        IF,
        IGNORE,
        IN,
        INDEX,
        INFILE,
        INNER,
        INOUT,
        INSENSITIVE,
        INSERT,
        INT,
        INT1,
        INT2,
        INT3,
        INT4,
        INT8,
        INTEGER,
        INTERVAL,
        INTO,
        IO_AFTER_GTIDS,
        IO_BEFORE_GTIDS,
        IS,
        ITERATE,
        JOIN,
        KEY,
        KEYS,
        KILL,
        LEADING,
        LEAVE,
        LEFT,
        LIKE,
        LIMIT,
        LINEAR,
        LINES,
        LOAD,
        LOCALTIME,
        LOCALTIMESTAMP,
        LOCK,
        LONG,
        LONGBLOB,
        LONGTEXT,
        LOOP,
        LOW_PRIORITY,
        MASTER_BIND,
        MASTER_SSL_VERIFY_SERVER_CERT,
        MATCH,
        MAXVALUE,
        MEDIUMBLOB,
        MEDIUMINT,
        MEDIUMTEXT,
        MIDDLEINT,
        MINUTE_MICROSECOND,
        MINUTE_SECOND,
        MOD,
        MODIFIES,
        NATURAL,
        NOT,
        NO_WRITE_TO_BINLOG,
        _NULL,
        NUMERIC,
        ON,
        OPTIMIZE,
        OPTIMIZER_COSTS,
        OPTION,
        OPTIONALLY,
        OR,
        ORDER,
        OUT,
        OUTER,
        OUTFILE,
        PARTITION,
        PRECISION,
        PRIMARY,
        PROCEDURE,
        PURGE,
        RANGE,
        READ,
        READS,
        READ_WRITE,
        REAL,
        REFERENCES,
        REGEXP,
        RELEASE,
        RENAME,
        REPEAT,
        REPLACE,
        REQUIRE,
        RESIGNAL,
        RESTRICT,
        RETURN,
        REVOKE,
        RIGHT,
        RLIKE,
        SCHEMA,
        SCHEMAS,
        SECOND_MICROSECOND,
        SELECT,
        SENSITIVE,
        SEPARATOR,
        SET,
        SHOW,
        SIGNAL,
        SMALLINT,
        SPATIAL,
        SPECIFIC,
        SQL,
        SQLEXCEPTION,
        SQLSTATE,
        SQLWARNING,
        SQL_BIG_RESULT,
        SQL_CALC_FOUND_ROWS,
        SQL_SMALL_RESULT,
        SSL,
        STARTING,
        STORED,
        STRAIGHT_JOIN,
        TABLE,
        TERMINATED,
        THEN,
        TINYBLOB,
        TINYINT,
        TINYTEXT,
        TO,
        TRAILING,
        TRIGGER,
        TRUE,
        UNDO,
        UNION,
        UNIQUE,
        UNLOCK,
        UNSIGNED,
        UPDATE,
        USAGE,
        USE,
        USING,
        UTC_DATE,
        UTC_TIME,
        UTC_TIMESTAMP,
        VALUES,
        VARBINARY,
        VARCHAR,
        VARCHARACTER,
        VARYING,
        VIRTUAL,
        WHEN,
        WHERE,
        WHILE,
        WITH,
        WRITE,
        XOR,
        YEAR_MONTH,
        ZEROFILL,
        END_OF_RESERVED_KEYWORD,
        START_OF_NON_RESERVED_KEYWORD,
        ACCOUNT,
        ACTION,
        AFTER,
        AGAINST,
        AGGREGATE,
        ALGORITHM,
        ALWAYS,
        ANALYSE,
        ANY,
        ASCII,
        AT,
        AUTOEXTEND_SIZE,
        AUTO_INCREMENT,
        AVG,
        AVG_ROW_LENGTH,
        BACKUP,
        BEGIN,
        BINLOG,
        BIT,
        BLOCK,
        BOOL,
        BOOLEAN,
        BTREE,
        BYTE,
        CACHE,
        CASCADED,
        CATALOG_NAME,
        CHAIN,
        CHANGED,
        CHANNEL,
        CHARSET,
        CHECKSUM,
        CIPHER,
        CLASS_ORIGIN,
        CLIENT,
        CLOSE,
        COALESCE,
        CODE,
        COLLATION,
        COLUMNS,
        COLUMN_FORMAT,
        COLUMN_NAME,
        COMMENT,
        COMMIT,
        COMMITTED,
        COMPACT,
        COMPLETION,
        COMPRESSED,
        COMPRESSION,
        CONCURRENT,
        CONNECTION,
        CONSISTENT,
        CONSTRAINT_CATALOG,
        CONSTRAINT_NAME,
        CONSTRAINT_SCHEMA,
        CONTAINS,
        CONTEXT,
        CPU,
        CUBE,
        CURRENT,
        CURSOR_NAME,
        DATA,
        DATAFILE,
        DATE,
        DATETIME,
        DAY,
        DEALLOCATE,
        DEFAULT_AUTH,
        DEFINER,
        DELAY_KEY_WRITE,
        DES_KEY_FILE,
        DIAGNOSTICS,
        DIRECTORY,
        DISABLE,
        DISCARD,
        DISK,
        DO,
        DUMPFILE,
        DUPLICATE,
        DYNAMIC,
        ENABLE,
        ENCRYPTION,
        END,
        ENDS,
        ENGINE,
        ENGINES,
        ENUM,
        ERROR,
        ERRORS,
        ESCAPE,
        EVENT,
        EVENTS,
        EVERY,
        EXCHANGE,
        EXECUTE,
        EXPANSION,
        EXPIRE,
        EXPORT,
        EXTENDED,
        EXTENT_SIZE,
        FAST,
        FAULTS,
        FIELDS,
        FILE,
        FILE_BLOCK_SIZE,
        FILTER,
        FIRST,
        FIXED,
        FLUSH,
        FOLLOWS,
        FORMAT,
        FOUND,
        FULL,
        FUNCTION,
        GENERAL,
        GEOMETRY,
        GEOMETRYCOLLECTION,
        GET_FORMAT,
        GLOBAL,
        GRANTS,
        GROUP_REPLICATION,
        HANDLER,
        HASH,
        HELP,
        HOST,
        HOSTS,
        HOUR,
        IDENTIFIED,
        IGNORE_SERVER_IDS,
        IMPORT,
        INDEXES,
        INITIAL_SIZE,
        INSERT_METHOD,
        INSTALL,
        INSTANCE,
        INVOKER,
        IO,
        IO_THREAD,
        IPC,
        ISOLATION,
        ISSUER,
        JSON,
        KEY_BLOCK_SIZE,
        LANGUAGE,
        LAST,
        LEAVES,
        LESS,
        LEVEL,
        LINESTRING,
        LIST,
        LOCAL,
        LOCKS,
        LOGFILE,
        LOGS,
        MASTER,
        MASTER_AUTO_POSITION,
        MASTER_CONNECT_RETRY,
        MASTER_DELAY,
        MASTER_HEARTBEAT_PERIOD,
        MASTER_HOST,
        MASTER_LOG_FILE,
        MASTER_LOG_POS,
        MASTER_PASSWORD,
        MASTER_PORT,
        MASTER_RETRY_COUNT,
        MASTER_SERVER_ID,
        MASTER_SSL,
        MASTER_SSL_CA,
        MASTER_SSL_CAPATH,
        MASTER_SSL_CERT,
        MASTER_SSL_CIPHER,
        MASTER_SSL_CRL,
        MASTER_SSL_CRLPATH,
        MASTER_SSL_KEY,
        MASTER_TLS_VERSION,
        MASTER_USER,
        MAX_CONNECTIONS_PER_HOUR,
        MAX_QUERIES_PER_HOUR,
        MAX_ROWS,
        MAX_SIZE,
        MAX_STATEMENT_TIME,
        MAX_UPDATES_PER_HOUR,
        MAX_USER_CONNECTIONS,
        MEDIUM,
        MEMORY,
        MERGE,
        MESSAGE_TEXT,
        MICROSECOND,
        MIGRATE,
        MINUTE,
        MIN_ROWS,
        MODE,
        MODIFY,
        MONTH,
        MULTILINESTRING,
        MULTIPOINT,
        MULTIPOLYGON,
        MUTEX,
        MYSQL_ERRNO,
        NAME,
        NAMES,
        NATIONAL,
        NCHAR,
        NDB,
        NDBCLUSTER,
        NEVER,
        NEW,
        NEXT,
        NO,
        NODEGROUP,
        NONBLOCKING,
        NONE,
        NO_WAIT,
        NUMBER,
        NVARCHAR,
        OFFSET,
        OLD_PASSWORD,
        ONE,
        ONLY,
        OPEN,
        OPTIONS,
        OWNER,
        PACK_KEYS,
        PAGE,
        PARSER,
        PARSE_GCOL_EXPR,
        PARTIAL,
        PARTITIONING,
        PARTITIONS,
        PASSWORD,
        PHASE,
        PLUGIN,
        PLUGINS,
        PLUGIN_DIR,
        POINT,
        POLYGON,
        PORT,
        PRECEDES,
        PREPARE,
        PRESERVE,
        PREV,
        PRIVILEGES,
        PROCESSLIST,
        PROFILE,
        PROFILES,
        PROXY,
        QUARTER,
        QUERY,
        QUICK,
        READ_ONLY,
        REBUILD,
        RECOVER,
        REDOFILE,
        REDO_BUFFER_SIZE,
        REDUNDANT,
        RELAY,
        RELAYLOG,
        RELAY_LOG_FILE,
        RELAY_LOG_POS,
        RELAY_THREAD,
        RELOAD,
        REMOVE,
        REORGANIZE,
        REPAIR,
        REPEATABLE,
        REPLICATE_DO_DB,
        REPLICATE_DO_TABLE,
        REPLICATE_IGNORE_DB,
        REPLICATE_IGNORE_TABLE,
        REPLICATE_REWRITE_DB,
        REPLICATE_WILD_DO_TABLE,
        REPLICATE_WILD_IGNORE_TABLE,
        REPLICATION,
        RESET,
        RESTORE,
        RESUME,
        RETURNED_SQLSTATE,
        RETURNS,
        REVERSE,
        ROLLBACK,
        ROLLUP,
        ROTATE,
        ROUTINE,
        ROW,
        ROWS,
        ROW_COUNT,
        ROW_FORMAT,
        RTREE,
        SAVEPOINT,
        SCHEDULE,
        SCHEMA_NAME,
        SECOND,
        SECURITY,
        SERIAL,
        SERIALIZABLE,
        SERVER,
        SESSION,
        SHARE,
        SHUTDOWN,
        SIGNED,
        SIMPLE,
        SLAVE,
        SLOW,
        SNAPSHOT,
        SOCKET,
        SOME,
        SONAME,
        SOUNDS,
        SOURCE,
        SQL_AFTER_GTIDS,
        SQL_AFTER_MTS_GAPS,
        SQL_BEFORE_GTIDS,
        SQL_BUFFER_RESULT,
        SQL_CACHE,
        SQL_NO_CACHE,
        SQL_THREAD,
        SQL_TSI_DAY,
        SQL_TSI_HOUR,
        SQL_TSI_MINUTE,
        SQL_TSI_MONTH,
        SQL_TSI_QUARTER,
        SQL_TSI_SECOND,
        SQL_TSI_WEEK,
        SQL_TSI_YEAR,
        STACKED,
        START,
        STARTS,
        STATS_AUTO_RECALC,
        STATS_PERSISTENT,
        STATS_SAMPLE_PAGES,
        STATUS,
        STOP,
        STORAGE,
        STRING,
        SUBCLASS_ORIGIN,
        SUBJECT,
        SUBPARTITION,
        SUBPARTITIONS,
        SUPER,
        SUSPEND,
        SWAPS,
        SWITCHES,
        TABLES,
        TABLESPACE,
        TABLE_CHECKSUM,
        TABLE_NAME,
        TEMPORARY,
        TEMPTABLE,
        TEXT,
        THAN,
        TIME,
        TIMESTAMP,
        TIMESTAMPADD,
        TIMESTAMPDIFF,
        TRANSACTION,
        TRIGGERS,
        TRUNCATE,
        TYPE,
        TYPES,
        UNCOMMITTED,
        UNDEFINED,
        UNDOFILE,
        UNDO_BUFFER_SIZE,
        UNICODE,
        UNINSTALL,
        UNKNOWN,
        UNTIL,
        UPGRADE,
        USER,
        USER_RESOURCES,
        USE_FRM,
        VALIDATION,
        VALUE,
        VARIABLES,
        VIEW,
        WAIT,
        WARNINGS,
        WEEK,
        WEIGHT_STRING,
        WITHOUT,
        WORK,
        WRAPPER,
        X509,
        XA,
        XID,
        XML,
        YEAR,
        END_OF_NON_RESERVED_KEYWORD,
        EndOfFile,
        UnknownToken,
        CustomDelimiter,
        SingleLineComment,
        MultiLineComment,
        ExecutionComment,
        WhiteSpace,
        LineBreak,
        StringLiteral,
        HexLiteral,
        BitLiteral,
        IntegerLiteral,
        DecimalLiteral,
        RealLiteral,
        Identifier,
        UserVariableIdentifier,
        MacroIdentifier,
        Plus,
        Minus,
        Asterisk,
        Percent,
        Slash,
        Colon,
        Dot,
        SemiColon,
        Comma,
        Pound,
        OpenParenthesesPound,
        PoundCloseParentheses,
        Backslash,
        QuestionMark,
        ColonEqual,
        AtAt,
        AtAtGlobalDot,
        AtAtSessionDot,
        Tilde,
        Caret,
        Bar,
        Equal,
        LessEqualGreater,
        GreaterEqual,
        Greater,
        LessEqual,
        Less,
        LessGreater,
        LessLess,
        GreaterGreater,
        OpenParentheses,
        CloseParentheses,
        OpenBrace,
        CloseBrace,
        DELIMITER_STATEMENT,
        UNIQUE_KEY
    };

    std::vector<std::string> reservedKeywords = {
        "ACCESSIBLE",
        "ADD",
        "ALL",
        "ALTER",
        "ANALYZE",
        "AND",
        "AS",
        "ASC",
        "ASENSITIVE",
        "BEFORE",
        "BETWEEN",
        "BIGINT",
        "BINARY",
        "BLOB",
        "BOTH",
        "BY",
        "CALL",
        "CASCADE",
        "CASE",
        "CHANGE",
        "CHAR",
        "CHARACTER",
        "CHECK",
        "COLLATE",
        "COLUMN",
        "CONDITION",
        "CONSTRAINT",
        "CONTINUE",
        "CONVERT",
        "CREATE",
        "CROSS",
        "CURRENT_DATE",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_USER",
        "CURSOR",
        "DATABASE",
        "DATABASES",
        "DAY_HOUR",
        "DAY_MICROSECOND",
        "DAY_MINUTE",
        "DAY_SECOND",
        "DEC",
        "DECIMAL",
        "DECLARE",
        "DEFAULT",
        "DELAYED",
        "DELETE",
        "DESC",
        "DESCRIBE",
        "DETERMINISTIC",
        "DISTINCT",
        "DISTINCTROW",
        "DIV",
        "DOUBLE",
        "DROP",
        "DUAL",
        "EACH",
        "ELSE",
        "ELSEIF",
        "ENCLOSED",
        "ESCAPED",
        "EXISTS",
        "EXIT",
        "EXPLAIN",
        "FALSE",
        "FETCH",
        "FLOAT",
        "FLOAT4",
        "FLOAT8",
        "FOR",
        "FORCE",
        "FOREIGN",
        "FROM",
        "FULLTEXT",
        "GENERATED",
        "GET",
        "GRANT",
        "GROUP",
        "HAVING",
        "HIGH_PRIORITY",
        "HOUR_MICROSECOND",
        "HOUR_MINUTE",
        "HOUR_SECOND",
        "IF",
        "IGNORE",
        "IN",
        "INDEX",
        "INFILE",
        "INNER",
        "INOUT",
        "INSENSITIVE",
        "INSERT",
        "INT",
        "INT1",
        "INT2",
        "INT3",
        "INT4",
        "INT8",
        "INTEGER",
        "INTERVAL",
        "INTO",
        "IO_AFTER_GTIDS",
        "IO_BEFORE_GTIDS",
        "IS",
        "ITERATE",
        "JOIN",
        "KEY",
        "KEYS",
        "KILL",
        "LEADING",
        "LEAVE",
        "LEFT",
        "LIKE",
        "LIMIT",
        "LINEAR",
        "LINES",
        "LOAD",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LOCK",
        "LONG",
        "LONGBLOB",
        "LONGTEXT",
        "LOOP",
        "LOW_PRIORITY",
        "MASTER_BIND",
        "MASTER_SSL_VERIFY_SERVER_CERT",
        "MATCH",
        "MAXVALUE",
        "MEDIUMBLOB",
        "MEDIUMINT",
        "MEDIUMTEXT",
        "MIDDLEINT",
        "MINUTE_MICROSECOND",
        "MINUTE_SECOND",
        "MOD",
        "MODIFIES",
        "NATURAL",
        "NOT",
        "NO_WRITE_TO_BINLOG",
        "NULL",
        "NUMERIC",
        "ON",
        "OPTIMIZE",
        "OPTIMIZER_COSTS",
        "OPTION",
        "OPTIONALLY",
        "OR",
        "ORDER",
        "OUT",
        "OUTER",
        "OUTFILE",
        "PARTITION",
        "PRECISION",
        "PRIMARY",
        "PROCEDURE",
        "PURGE",
        "RANGE",
        "READ",
        "READS",
        "READ_WRITE",
        "REAL",
        "REFERENCES",
        "REGEXP",
        "RELEASE",
        "RENAME",
        "REPEAT",
        "REPLACE",
        "REQUIRE",
        "RESIGNAL",
        "RESTRICT",
        "RETURN",
        "REVOKE",
        "RIGHT",
        "RLIKE",
        "SCHEMA",
        "SCHEMAS",
        "SECOND_MICROSECOND",
        "SELECT",
        "SENSITIVE",
        "SEPARATOR",
        "SET",
        "SHOW",
        "SIGNAL",
        "SMALLINT",
        "SPATIAL",
        "SPECIFIC",
        "SQL",
        "SQLEXCEPTION",
        "SQLSTATE",
        "SQLWARNING",
        "SQL_BIG_RESULT",
        "SQL_CALC_FOUND_ROWS",
        "SQL_SMALL_RESULT",
        "SSL",
        "STARTING",
        "STORED",
        "STRAIGHT_JOIN",
        "TABLE",
        "TERMINATED",
        "THEN",
        "TINYBLOB",
        "TINYINT",
        "TINYTEXT",
        "TO",
        "TRAILING",
        "TRIGGER",
        "TRUE",
        "UNDO",
        "UNION",
        "UNIQUE",
        "UNLOCK",
        "UNSIGNED",
        "UPDATE",
        "USAGE",
        "USE",
        "USING",
        "UTC_DATE",
        "UTC_TIME",
        "UTC_TIMESTAMP",
        "VALUES",
        "VARBINARY",
        "VARCHAR",
        "VARCHARACTER",
        "VARYING",
        "VIRTUAL",
        "WHEN",
        "WHERE",
        "WHILE",
        "WITH",
        "WRITE",
        "XOR",
        "YEAR_MONTH",
        "ZEROFILL"
    };

    std::vector<std::string> nonReservedKeywords = {
        "ACCOUNT",
        "ACTION",
        "AFTER",
        "AGAINST",
        "AGGREGATE",
        "ALGORITHM",
        "ALWAYS",
        "ANALYSE",
        "ANY",
        "ASCII",
        "AT",
        "AUTOEXTEND_SIZE",
        "AUTO_INCREMENT",
        "AVG",
        "AVG_ROW_LENGTH",
        "BACKUP",
        "BEGIN",
        "BINLOG",
        "BIT",
        "BLOCK",
        "BOOL",
        "BOOLEAN",
        "BTREE",
        "BYTE",
        "CACHE",
        "CASCADED",
        "CATALOG_NAME",
        "CHAIN",
        "CHANGED",
        "CHANNEL",
        "CHARSET",
        "CHECKSUM",
        "CIPHER",
        "CLASS_ORIGIN",
        "CLIENT",
        "CLOSE",
        "COALESCE",
        "CODE",
        "COLLATION",
        "COLUMNS",
        "COLUMN_FORMAT",
        "COLUMN_NAME",
        "COMMENT",
        "COMMIT",
        "COMMITTED",
        "COMPACT",
        "COMPLETION",
        "COMPRESSED",
        "COMPRESSION",
        "CONCURRENT",
        "CONNECTION",
        "CONSISTENT",
        "CONSTRAINT_CATALOG",
        "CONSTRAINT_NAME",
        "CONSTRAINT_SCHEMA",
        "CONTAINS",
        "CONTEXT",
        "CPU",
        "CUBE",
        "CURRENT",
        "CURSOR_NAME",
        "DATA",
        "DATAFILE",
        "DATE",
        "DATETIME",
        "DAY",
        "DEALLOCATE",
        "DEFAULT_AUTH",
        "DEFINER",
        "DELAY_KEY_WRITE",
        "DES_KEY_FILE",
        "DIAGNOSTICS",
        "DIRECTORY",
        "DISABLE",
        "DISCARD",
        "DISK",
        "DO",
        "DUMPFILE",
        "DUPLICATE",
        "DYNAMIC",
        "ENABLE",
        "ENCRYPTION",
        "END",
        "ENDS",
        "ENGINE",
        "ENGINES",
        "ENUM",
        "ERROR",
        "ERRORS",
        "ESCAPE",
        "EVENT",
        "EVENTS",
        "EVERY",
        "EXCHANGE",
        "EXECUTE",
        "EXPANSION",
        "EXPIRE",
        "EXPORT",
        "EXTENDED",
        "EXTENT_SIZE",
        "FAST",
        "FAULTS",
        "FIELDS",
        "FILE",
        "FILE_BLOCK_SIZE",
        "FILTER",
        "FIRST",
        "FIXED",
        "FLUSH",
        "FOLLOWS",
        "FORMAT",
        "FOUND",
        "FULL",
        "FUNCTION",
        "GENERAL",
        "GEOMETRY",
        "GEOMETRYCOLLECTION",
        "GET_FORMAT",
        "GLOBAL",
        "GRANTS",
        "GROUP_REPLICATION",
        "HANDLER",
        "HASH",
        "HELP",
        "HOST",
        "HOSTS",
        "HOUR",
        "IDENTIFIED",
        "IGNORE_SERVER_IDS",
        "IMPORT",
        "INDEXES",
        "INITIAL_SIZE",
        "INSERT_METHOD",
        "INSTALL",
        "INSTANCE",
        "INVOKER",
        "IO",
        "IO_THREAD",
        "IPC",
        "ISOLATION",
        "ISSUER",
        "JSON",
        "KEY_BLOCK_SIZE",
        "LANGUAGE",
        "LAST",
        "LEAVES",
        "LESS",
        "LEVEL",
        "LINESTRING",
        "LIST",
        "LOCAL",
        "LOCKS",
        "LOGFILE",
        "LOGS",
        "MASTER",
        "MASTER_AUTO_POSITION",
        "MASTER_CONNECT_RETRY",
        "MASTER_DELAY",
        "MASTER_HEARTBEAT_PERIOD",
        "MASTER_HOST",
        "MASTER_LOG_FILE",
        "MASTER_LOG_POS",
        "MASTER_PASSWORD",
        "MASTER_PORT",
        "MASTER_RETRY_COUNT",
        "MASTER_SERVER_ID",
        "MASTER_SSL",
        "MASTER_SSL_CA",
        "MASTER_SSL_CAPATH",
        "MASTER_SSL_CERT",
        "MASTER_SSL_CIPHER",
        "MASTER_SSL_CRL",
        "MASTER_SSL_CRLPATH",
        "MASTER_SSL_KEY",
        "MASTER_TLS_VERSION",
        "MASTER_USER",
        "MAX_CONNECTIONS_PER_HOUR",
        "MAX_QUERIES_PER_HOUR",
        "MAX_ROWS",
        "MAX_SIZE",
        "MAX_STATEMENT_TIME",
        "MAX_UPDATES_PER_HOUR",
        "MAX_USER_CONNECTIONS",
        "MEDIUM",
        "MEMORY",
        "MERGE",
        "MESSAGE_TEXT",
        "MICROSECOND",
        "MIGRATE",
        "MINUTE",
        "MIN_ROWS",
        "MODE",
        "MODIFY",
        "MONTH",
        "MULTILINESTRING",
        "MULTIPOINT",
        "MULTIPOLYGON",
        "MUTEX",
        "MYSQL_ERRNO",
        "NAME",
        "NAMES",
        "NATIONAL",
        "NCHAR",
        "NDB",
        "NDBCLUSTER",
        "NEVER",
        "NEW",
        "NEXT",
        "NO",
        "NODEGROUP",
        "NONBLOCKING",
        "NONE",
        "NO_WAIT",
        "NUMBER",
        "NVARCHAR",
        "OFFSET",
        "OLD_PASSWORD",
        "ONE",
        "ONLY",
        "OPEN",
        "OPTIONS",
        "OWNER",
        "PACK_KEYS",
        "PAGE",
        "PARSER",
        "PARSE_GCOL_EXPR",
        "PARTIAL",
        "PARTITIONING",
        "PARTITIONS",
        "PASSWORD",
        "PHASE",
        "PLUGIN",
        "PLUGINS",
        "PLUGIN_DIR",
        "POINT",
        "POLYGON",
        "PORT",
        "PRECEDES",
        "PREPARE",
        "PRESERVE",
        "PREV",
        "PRIVILEGES",
        "PROCESSLIST",
        "PROFILE",
        "PROFILES",
        "PROXY",
        "QUARTER",
        "QUERY",
        "QUICK",
        "READ_ONLY",
        "REBUILD",
        "RECOVER",
        "REDOFILE",
        "REDO_BUFFER_SIZE",
        "REDUNDANT",
        "RELAY",
        "RELAYLOG",
        "RELAY_LOG_FILE",
        "RELAY_LOG_POS",
        "RELAY_THREAD",
        "RELOAD",
        "REMOVE",
        "REORGANIZE",
        "REPAIR",
        "REPEATABLE",
        "REPLICATE_DO_DB",
        "REPLICATE_DO_TABLE",
        "REPLICATE_IGNORE_DB",
        "REPLICATE_IGNORE_TABLE",
        "REPLICATE_REWRITE_DB",
        "REPLICATE_WILD_DO_TABLE",
        "REPLICATE_WILD_IGNORE_TABLE",
        "REPLICATION",
        "RESET",
        "RESTORE",
        "RESUME",
        "RETURNED_SQLSTATE",
        "RETURNS",
        "REVERSE",
        "ROLLBACK",
        "ROLLUP",
        "ROTATE",
        "ROUTINE",
        "ROW",
        "ROWS",
        "ROW_COUNT",
        "ROW_FORMAT",
        "RTREE",
        "SAVEPOINT",
        "SCHEDULE",
        "SCHEMA_NAME",
        "SECOND",
        "SECURITY",
        "SERIAL",
        "SERIALIZABLE",
        "SERVER",
        "SESSION",
        "SHARE",
        "SHUTDOWN",
        "SIGNED",
        "SIMPLE",
        "SLAVE",
        "SLOW",
        "SNAPSHOT",
        "SOCKET",
        "SOME",
        "SONAME",
        "SOUNDS",
        "SOURCE",
        "SQL_AFTER_GTIDS",
        "SQL_AFTER_MTS_GAPS",
        "SQL_BEFORE_GTIDS",
        "SQL_BUFFER_RESULT",
        "SQL_CACHE",
        "SQL_NO_CACHE",
        "SQL_THREAD",
        "SQL_TSI_DAY",
        "SQL_TSI_HOUR",
        "SQL_TSI_MINUTE",
        "SQL_TSI_MONTH",
        "SQL_TSI_QUARTER",
        "SQL_TSI_SECOND",
        "SQL_TSI_WEEK",
        "SQL_TSI_YEAR",
        "STACKED",
        "START",
        "STARTS",
        "STATS_AUTO_RECALC",
        "STATS_PERSISTENT",
        "STATS_SAMPLE_PAGES",
        "STATUS",
        "STOP",
        "STORAGE",
        "STRING",
        "SUBCLASS_ORIGIN",
        "SUBJECT",
        "SUBPARTITION",
        "SUBPARTITIONS",
        "SUPER",
        "SUSPEND",
        "SWAPS",
        "SWITCHES",
        "TABLES",
        "TABLESPACE",
        "TABLE_CHECKSUM",
        "TABLE_NAME",
        "TEMPORARY",
        "TEMPTABLE",
        "TEXT",
        "THAN",
        "TIME",
        "TIMESTAMP",
        "TIMESTAMPADD",
        "TIMESTAMPDIFF",
        "TRANSACTION",
        "TRIGGERS",
        "TRUNCATE",
        "TYPE",
        "TYPES",
        "UNCOMMITTED",
        "UNDEFINED",
        "UNDOFILE",
        "UNDO_BUFFER_SIZE",
        "UNICODE",
        "UNINSTALL",
        "UNKNOWN",
        "UNTIL",
        "UPGRADE",
        "USER",
        "USER_RESOURCES",
        "USE_FRM",
        "VALIDATION",
        "VALUE",
        "VARIABLES",
        "VIEW",
        "WAIT",
        "WARNINGS",
        "WEEK",
        "WEIGHT_STRING",
        "WITHOUT",
        "WORK",
        "WRAPPER",
        "X509",
        "XA",
        "XID",
        "XML",
        "YEAR"
    };

    struct ci_less
    {
        // case-independent (ci) compare_less binary function
        struct nocase_compare
        {
            bool operator() (const unsigned char& c1, const unsigned char& c2) const {
                return tolower(c1) < tolower(c2);
            }
        };
        bool operator() (std::string const &s1, std::string const &s2) const {
            return std::lexicographical_compare(
                s1.begin(),
                s1.end(),   // source range
                s2.begin(),
                s2.end(),   // dest range
                nocase_compare()
            );  // comparison
        }
    };

    std::map<std::string, TokenType, ci_less> keyword2TokenType = {
        { "ACCESSIBLE", TokenType::ACCESSIBLE },
        { "ADD", TokenType::ADD },
        { "ALL", TokenType::ALL },
        { "ALTER", TokenType::ALTER },
        { "ANALYZE", TokenType::ANALYZE },
        { "AND", TokenType::AND },
        { "AS", TokenType::AS },
        { "ASC", TokenType::ASC },
        { "ASENSITIVE", TokenType::ASENSITIVE },
        { "BEFORE", TokenType::BEFORE },
        { "BETWEEN", TokenType::BETWEEN },
        { "BIGINT", TokenType::BIGINT },
        { "BINARY", TokenType::BINARY },
        { "BLOB", TokenType::BLOB },
        { "BOTH", TokenType::BOTH },
        { "BY", TokenType::BY },
        { "CALL", TokenType::CALL },
        { "CASCADE", TokenType::CASCADE },
        { "CASE", TokenType::CASE },
        { "CHANGE", TokenType::CHANGE },
        { "CHAR", TokenType::CHAR },
        { "CHARACTER", TokenType::CHARACTER },
        { "CHECK", TokenType::CHECK },
        { "COLLATE", TokenType::COLLATE },
        { "COLUMN", TokenType::COLUMN },
        { "CONDITION", TokenType::CONDITION },
        { "CONSTRAINT", TokenType::CONSTRAINT },
        { "CONTINUE", TokenType::CONTINUE },
        { "CONVERT", TokenType::CONVERT },
        { "CREATE", TokenType::CREATE },
        { "CROSS", TokenType::CROSS },
        { "CURRENT_DATE", TokenType::CURRENT_DATE },
        { "CURRENT_TIME", TokenType::CURRENT_TIME },
        { "CURRENT_TIMESTAMP", TokenType::CURRENT_TIMESTAMP },
        { "CURRENT_USER", TokenType::CURRENT_USER },
        { "CURSOR", TokenType::CURSOR },
        { "DATABASE", TokenType::DATABASE },
        { "DATABASES", TokenType::DATABASES },
        { "DAY_HOUR", TokenType::DAY_HOUR },
        { "DAY_MICROSECOND", TokenType::DAY_MICROSECOND },
        { "DAY_MINUTE", TokenType::DAY_MINUTE },
        { "DAY_SECOND", TokenType::DAY_SECOND },
        { "DEC", TokenType::DEC },
        { "DECIMAL", TokenType::DECIMAL },
        { "DECLARE", TokenType::DECLARE },
        { "DEFAULT", TokenType::DEFAULT },
        { "DELAYED", TokenType::DELAYED },
        { "DELETE", TokenType::DELETE },
        { "DESC", TokenType::DESC },
        { "DESCRIBE", TokenType::DESCRIBE },
        { "DETERMINISTIC", TokenType::DETERMINISTIC },
        { "DISTINCT", TokenType::DISTINCT },
        { "DISTINCTROW", TokenType::DISTINCTROW },
        { "DIV", TokenType::DIV },
        { "DOUBLE", TokenType::DOUBLE },
        { "DROP", TokenType::DROP },
        { "DUAL", TokenType::DUAL },
        { "EACH", TokenType::EACH },
        { "ELSE", TokenType::ELSE },
        { "ELSEIF", TokenType::ELSEIF },
        { "ENCLOSED", TokenType::ENCLOSED },
        { "ESCAPED", TokenType::ESCAPED },
        { "EXISTS", TokenType::EXISTS },
        { "EXIT", TokenType::EXIT },
        { "EXPLAIN", TokenType::EXPLAIN },
        { "FALSE", TokenType::FALSE },
        { "FETCH", TokenType::FETCH },
        { "FLOAT", TokenType::FLOAT },
        { "FLOAT4", TokenType::FLOAT4 },
        { "FLOAT8", TokenType::FLOAT8 },
        { "FOR", TokenType::FOR },
        { "FORCE", TokenType::FORCE },
        { "FOREIGN", TokenType::FOREIGN },
        { "FROM", TokenType::FROM },
        { "FULLTEXT", TokenType::FULLTEXT },
        { "GENERATED", TokenType::GENERATED },
        { "GET", TokenType::GET },
        { "GRANT", TokenType::GRANT },
        { "GROUP", TokenType::GROUP },
        { "HAVING", TokenType::HAVING },
        { "HIGH_PRIORITY", TokenType::HIGH_PRIORITY },
        { "HOUR_MICROSECOND", TokenType::HOUR_MICROSECOND },
        { "HOUR_MINUTE", TokenType::HOUR_MINUTE },
        { "HOUR_SECOND", TokenType::HOUR_SECOND },
        { "IF", TokenType::IF },
        { "IGNORE", TokenType::IGNORE },
        { "IN", TokenType::IN },
        { "INDEX", TokenType::INDEX },
        { "INFILE", TokenType::INFILE },
        { "INNER", TokenType::INNER },
        { "INOUT", TokenType::INOUT },
        { "INSENSITIVE", TokenType::INSENSITIVE },
        { "INSERT", TokenType::INSERT },
        { "INT", TokenType::INT },
        { "INT1", TokenType::INT1 },
        { "INT2", TokenType::INT2 },
        { "INT3", TokenType::INT3 },
        { "INT4", TokenType::INT4 },
        { "INT8", TokenType::INT8 },
        { "INTEGER", TokenType::INTEGER },
        { "INTERVAL", TokenType::INTERVAL },
        { "INTO", TokenType::INTO },
        { "IO_AFTER_GTIDS", TokenType::IO_AFTER_GTIDS },
        { "IO_BEFORE_GTIDS", TokenType::IO_BEFORE_GTIDS },
        { "IS", TokenType::IS },
        { "ITERATE", TokenType::ITERATE },
        { "JOIN", TokenType::JOIN },
        { "KEY", TokenType::KEY },
        { "KEYS", TokenType::KEYS },
        { "KILL", TokenType::KILL },
        { "LEADING", TokenType::LEADING },
        { "LEAVE", TokenType::LEAVE },
        { "LEFT", TokenType::LEFT },
        { "LIKE", TokenType::LIKE },
        { "LIMIT", TokenType::LIMIT },
        { "LINEAR", TokenType::LINEAR },
        { "LINES", TokenType::LINES },
        { "LOAD", TokenType::LOAD },
        { "LOCALTIME", TokenType::LOCALTIME },
        { "LOCALTIMESTAMP", TokenType::LOCALTIMESTAMP },
        { "LOCK", TokenType::LOCK },
        { "LONG", TokenType::LONG },
        { "LONGBLOB", TokenType::LONGBLOB },
        { "LONGTEXT", TokenType::LONGTEXT },
        { "LOOP", TokenType::LOOP },
        { "LOW_PRIORITY", TokenType::LOW_PRIORITY },
        { "MASTER_BIND", TokenType::MASTER_BIND },
        { "MASTER_SSL_VERIFY_SERVER_CERT", TokenType::MASTER_SSL_VERIFY_SERVER_CERT },
        { "MATCH", TokenType::MATCH },
        { "MAXVALUE", TokenType::MAXVALUE },
        { "MEDIUMBLOB", TokenType::MEDIUMBLOB },
        { "MEDIUMINT", TokenType::MEDIUMINT },
        { "MEDIUMTEXT", TokenType::MEDIUMTEXT },
        { "MIDDLEINT", TokenType::MIDDLEINT },
        { "MINUTE_MICROSECOND", TokenType::MINUTE_MICROSECOND },
        { "MINUTE_SECOND", TokenType::MINUTE_SECOND },
        { "MOD", TokenType::MOD },
        { "MODIFIES", TokenType::MODIFIES },
        { "NATURAL", TokenType::NATURAL },
        { "NOT", TokenType::NOT },
        { "NO_WRITE_TO_BINLOG", TokenType::NO_WRITE_TO_BINLOG },
        { "NULL", TokenType::_NULL },
        { "NUMERIC", TokenType::NUMERIC },
        { "ON", TokenType::ON },
        { "OPTIMIZE", TokenType::OPTIMIZE },
        { "OPTIMIZER_COSTS", TokenType::OPTIMIZER_COSTS },
        { "OPTION", TokenType::OPTION },
        { "OPTIONALLY", TokenType::OPTIONALLY },
        { "OR", TokenType::OR },
        { "ORDER", TokenType::ORDER },
        { "OUT", TokenType::OUT },
        { "OUTER", TokenType::OUTER },
        { "OUTFILE", TokenType::OUTFILE },
        { "PARTITION", TokenType::PARTITION },
        { "PRECISION", TokenType::PRECISION },
        { "PRIMARY", TokenType::PRIMARY },
        { "PROCEDURE", TokenType::PROCEDURE },
        { "PURGE", TokenType::PURGE },
        { "RANGE", TokenType::RANGE },
        { "READ", TokenType::READ },
        { "READS", TokenType::READS },
        { "READ_WRITE", TokenType::READ_WRITE },
        { "REAL", TokenType::REAL },
        { "REFERENCES", TokenType::REFERENCES },
        { "REGEXP", TokenType::REGEXP },
        { "RELEASE", TokenType::RELEASE },
        { "RENAME", TokenType::RENAME },
        { "REPEAT", TokenType::REPEAT },
        { "REPLACE", TokenType::REPLACE },
        { "REQUIRE", TokenType::REQUIRE },
        { "RESIGNAL", TokenType::RESIGNAL },
        { "RESTRICT", TokenType::RESTRICT },
        { "RETURN", TokenType::RETURN },
        { "REVOKE", TokenType::REVOKE },
        { "RIGHT", TokenType::RIGHT },
        { "RLIKE", TokenType::RLIKE },
        { "SCHEMA", TokenType::SCHEMA },
        { "SCHEMAS", TokenType::SCHEMAS },
        { "SECOND_MICROSECOND", TokenType::SECOND_MICROSECOND },
        { "SELECT", TokenType::SELECT },
        { "SENSITIVE", TokenType::SENSITIVE },
        { "SEPARATOR", TokenType::SEPARATOR },
        { "SET", TokenType::SET },
        { "SHOW", TokenType::SHOW },
        { "SIGNAL", TokenType::SIGNAL },
        { "SMALLINT", TokenType::SMALLINT },
        { "SPATIAL", TokenType::SPATIAL },
        { "SPECIFIC", TokenType::SPECIFIC },
        { "SQL", TokenType::SQL },
        { "SQLEXCEPTION", TokenType::SQLEXCEPTION },
        { "SQLSTATE", TokenType::SQLSTATE },
        { "SQLWARNING", TokenType::SQLWARNING },
        { "SQL_BIG_RESULT", TokenType::SQL_BIG_RESULT },
        { "SQL_CALC_FOUND_ROWS", TokenType::SQL_CALC_FOUND_ROWS },
        { "SQL_SMALL_RESULT", TokenType::SQL_SMALL_RESULT },
        { "SSL", TokenType::SSL },
        { "STARTING", TokenType::STARTING },
        { "STORED", TokenType::STORED },
        { "STRAIGHT_JOIN", TokenType::STRAIGHT_JOIN },
        { "TABLE", TokenType::TABLE },
        { "TERMINATED", TokenType::TERMINATED },
        { "THEN", TokenType::THEN },
        { "TINYBLOB", TokenType::TINYBLOB },
        { "TINYINT", TokenType::TINYINT },
        { "TINYTEXT", TokenType::TINYTEXT },
        { "TO", TokenType::TO },
        { "TRAILING", TokenType::TRAILING },
        { "TRIGGER", TokenType::TRIGGER },
        { "TRUE", TokenType::TRUE },
        { "UNDO", TokenType::UNDO },
        { "UNION", TokenType::UNION },
        { "UNIQUE", TokenType::UNIQUE },
        { "UNLOCK", TokenType::UNLOCK },
        { "UNSIGNED", TokenType::UNSIGNED },
        { "UPDATE", TokenType::UPDATE },
        { "USAGE", TokenType::USAGE },
        { "USE", TokenType::USE },
        { "USING", TokenType::USING },
        { "UTC_DATE", TokenType::UTC_DATE },
        { "UTC_TIME", TokenType::UTC_TIME },
        { "UTC_TIMESTAMP", TokenType::UTC_TIMESTAMP },
        { "VALUES", TokenType::VALUES },
        { "VARBINARY", TokenType::VARBINARY },
        { "VARCHAR", TokenType::VARCHAR },
        { "VARCHARACTER", TokenType::VARCHARACTER },
        { "VARYING", TokenType::VARYING },
        { "VIRTUAL", TokenType::VIRTUAL },
        { "WHEN", TokenType::WHEN },
        { "WHERE", TokenType::WHERE },
        { "WHILE", TokenType::WHILE },
        { "WITH", TokenType::WITH },
        { "WRITE", TokenType::WRITE },
        { "XOR", TokenType::XOR },
        { "YEAR_MONTH", TokenType::YEAR_MONTH },
        { "ZEROFILL", TokenType::ZEROFILL },
        { "ACCOUNT", TokenType::ACCOUNT },
        { "ACTION", TokenType::ACTION },
        { "AFTER", TokenType::AFTER },
        { "AGAINST", TokenType::AGAINST },
        { "AGGREGATE", TokenType::AGGREGATE },
        { "ALGORITHM", TokenType::ALGORITHM },
        { "ALWAYS", TokenType::ALWAYS },
        { "ANALYSE", TokenType::ANALYSE },
        { "ANY", TokenType::ANY },
        { "ASCII", TokenType::ASCII },
        { "AT", TokenType::AT },
        { "AUTOEXTEND_SIZE", TokenType::AUTOEXTEND_SIZE },
        { "AUTO_INCREMENT", TokenType::AUTO_INCREMENT },
        { "AVG", TokenType::AVG },
        { "AVG_ROW_LENGTH", TokenType::AVG_ROW_LENGTH },
        { "BACKUP", TokenType::BACKUP },
        { "BEGIN", TokenType::BEGIN },
        { "BINLOG", TokenType::BINLOG },
        { "BIT", TokenType::BIT },
        { "BLOCK", TokenType::BLOCK },
        { "BOOL", TokenType::BOOL },
        { "BOOLEAN", TokenType::BOOLEAN },
        { "BTREE", TokenType::BTREE },
        { "BYTE", TokenType::BYTE },
        { "CACHE", TokenType::CACHE },
        { "CASCADED", TokenType::CASCADED },
        { "CATALOG_NAME", TokenType::CATALOG_NAME },
        { "CHAIN", TokenType::CHAIN },
        { "CHANGED", TokenType::CHANGED },
        { "CHANNEL", TokenType::CHANNEL },
        { "CHARSET", TokenType::CHARSET },
        { "CHECKSUM", TokenType::CHECKSUM },
        { "CIPHER", TokenType::CIPHER },
        { "CLASS_ORIGIN", TokenType::CLASS_ORIGIN },
        { "CLIENT", TokenType::CLIENT },
        { "CLOSE", TokenType::CLOSE },
        { "COALESCE", TokenType::COALESCE },
        { "CODE", TokenType::CODE },
        { "COLLATION", TokenType::COLLATION },
        { "COLUMNS", TokenType::COLUMNS },
        { "COLUMN_FORMAT", TokenType::COLUMN_FORMAT },
        { "COLUMN_NAME", TokenType::COLUMN_NAME },
        { "COMMENT", TokenType::COMMENT },
        { "COMMIT", TokenType::COMMIT },
        { "COMMITTED", TokenType::COMMITTED },
        { "COMPACT", TokenType::COMPACT },
        { "COMPLETION", TokenType::COMPLETION },
        { "COMPRESSED", TokenType::COMPRESSED },
        { "COMPRESSION", TokenType::COMPRESSION },
        { "CONCURRENT", TokenType::CONCURRENT },
        { "CONNECTION", TokenType::CONNECTION },
        { "CONSISTENT", TokenType::CONSISTENT },
        { "CONSTRAINT_CATALOG", TokenType::CONSTRAINT_CATALOG },
        { "CONSTRAINT_NAME", TokenType::CONSTRAINT_NAME },
        { "CONSTRAINT_SCHEMA", TokenType::CONSTRAINT_SCHEMA },
        { "CONTAINS", TokenType::CONTAINS },
        { "CONTEXT", TokenType::CONTEXT },
        { "CPU", TokenType::CPU },
        { "CUBE", TokenType::CUBE },
        { "CURRENT", TokenType::CURRENT },
        { "CURSOR_NAME", TokenType::CURSOR_NAME },
        { "DATA", TokenType::DATA },
        { "DATAFILE", TokenType::DATAFILE },
        { "DATE", TokenType::DATE },
        { "DATETIME", TokenType::DATETIME },
        { "DAY", TokenType::DAY },
        { "DEALLOCATE", TokenType::DEALLOCATE },
        { "DEFAULT_AUTH", TokenType::DEFAULT_AUTH },
        { "DEFINER", TokenType::DEFINER },
        { "DELAY_KEY_WRITE", TokenType::DELAY_KEY_WRITE },
        { "DES_KEY_FILE", TokenType::DES_KEY_FILE },
        { "DIAGNOSTICS", TokenType::DIAGNOSTICS },
        { "DIRECTORY", TokenType::DIRECTORY },
        { "DISABLE", TokenType::DISABLE },
        { "DISCARD", TokenType::DISCARD },
        { "DISK", TokenType::DISK },
        { "DO", TokenType::DO },
        { "DUMPFILE", TokenType::DUMPFILE },
        { "DUPLICATE", TokenType::DUPLICATE },
        { "DYNAMIC", TokenType::DYNAMIC },
        { "ENABLE", TokenType::ENABLE },
        { "ENCRYPTION", TokenType::ENCRYPTION },
        { "END", TokenType::END },
        { "ENDS", TokenType::ENDS },
        { "ENGINE", TokenType::ENGINE },
        { "ENGINES", TokenType::ENGINES },
        { "ENUM", TokenType::ENUM },
        { "ERROR", TokenType::ERROR },
        { "ERRORS", TokenType::ERRORS },
        { "ESCAPE", TokenType::ESCAPE },
        { "EVENT", TokenType::EVENT },
        { "EVENTS", TokenType::EVENTS },
        { "EVERY", TokenType::EVERY },
        { "EXCHANGE", TokenType::EXCHANGE },
        { "EXECUTE", TokenType::EXECUTE },
        { "EXPANSION", TokenType::EXPANSION },
        { "EXPIRE", TokenType::EXPIRE },
        { "EXPORT", TokenType::EXPORT },
        { "EXTENDED", TokenType::EXTENDED },
        { "EXTENT_SIZE", TokenType::EXTENT_SIZE },
        { "FAST", TokenType::FAST },
        { "FAULTS", TokenType::FAULTS },
        { "FIELDS", TokenType::FIELDS },
        { "FILE", TokenType::FILE },
        { "FILE_BLOCK_SIZE", TokenType::FILE_BLOCK_SIZE },
        { "FILTER", TokenType::FILTER },
        { "FIRST", TokenType::FIRST },
        { "FIXED", TokenType::FIXED },
        { "FLUSH", TokenType::FLUSH },
        { "FOLLOWS", TokenType::FOLLOWS },
        { "FORMAT", TokenType::FORMAT },
        { "FOUND", TokenType::FOUND },
        { "FULL", TokenType::FULL },
        { "FUNCTION", TokenType::FUNCTION },
        { "GENERAL", TokenType::GENERAL },
        { "GEOMETRY", TokenType::GEOMETRY },
        { "GEOMETRYCOLLECTION", TokenType::GEOMETRYCOLLECTION },
        { "GET_FORMAT", TokenType::GET_FORMAT },
        { "GLOBAL", TokenType::GLOBAL },
        { "GRANTS", TokenType::GRANTS },
        { "GROUP_REPLICATION", TokenType::GROUP_REPLICATION },
        { "HANDLER", TokenType::HANDLER },
        { "HASH", TokenType::HASH },
        { "HELP", TokenType::HELP },
        { "HOST", TokenType::HOST },
        { "HOSTS", TokenType::HOSTS },
        { "HOUR", TokenType::HOUR },
        { "IDENTIFIED", TokenType::IDENTIFIED },
        { "IGNORE_SERVER_IDS", TokenType::IGNORE_SERVER_IDS },
        { "IMPORT", TokenType::IMPORT },
        { "INDEXES", TokenType::INDEXES },
        { "INITIAL_SIZE", TokenType::INITIAL_SIZE },
        { "INSERT_METHOD", TokenType::INSERT_METHOD },
        { "INSTALL", TokenType::INSTALL },
        { "INSTANCE", TokenType::INSTANCE },
        { "INVOKER", TokenType::INVOKER },
        { "IO", TokenType::IO },
        { "IO_THREAD", TokenType::IO_THREAD },
        { "IPC", TokenType::IPC },
        { "ISOLATION", TokenType::ISOLATION },
        { "ISSUER", TokenType::ISSUER },
        { "JSON", TokenType::JSON },
        { "KEY_BLOCK_SIZE", TokenType::KEY_BLOCK_SIZE },
        { "LANGUAGE", TokenType::LANGUAGE },
        { "LAST", TokenType::LAST },
        { "LEAVES", TokenType::LEAVES },
        { "LESS", TokenType::LESS },
        { "LEVEL", TokenType::LEVEL },
        { "LINESTRING", TokenType::LINESTRING },
        { "LIST", TokenType::LIST },
        { "LOCAL", TokenType::LOCAL },
        { "LOCKS", TokenType::LOCKS },
        { "LOGFILE", TokenType::LOGFILE },
        { "LOGS", TokenType::LOGS },
        { "MASTER", TokenType::MASTER },
        { "MASTER_AUTO_POSITION", TokenType::MASTER_AUTO_POSITION },
        { "MASTER_CONNECT_RETRY", TokenType::MASTER_CONNECT_RETRY },
        { "MASTER_DELAY", TokenType::MASTER_DELAY },
        { "MASTER_HEARTBEAT_PERIOD", TokenType::MASTER_HEARTBEAT_PERIOD },
        { "MASTER_HOST", TokenType::MASTER_HOST },
        { "MASTER_LOG_FILE", TokenType::MASTER_LOG_FILE },
        { "MASTER_LOG_POS", TokenType::MASTER_LOG_POS },
        { "MASTER_PASSWORD", TokenType::MASTER_PASSWORD },
        { "MASTER_PORT", TokenType::MASTER_PORT },
        { "MASTER_RETRY_COUNT", TokenType::MASTER_RETRY_COUNT },
        { "MASTER_SERVER_ID", TokenType::MASTER_SERVER_ID },
        { "MASTER_SSL", TokenType::MASTER_SSL },
        { "MASTER_SSL_CA", TokenType::MASTER_SSL_CA },
        { "MASTER_SSL_CAPATH", TokenType::MASTER_SSL_CAPATH },
        { "MASTER_SSL_CERT", TokenType::MASTER_SSL_CERT },
        { "MASTER_SSL_CIPHER", TokenType::MASTER_SSL_CIPHER },
        { "MASTER_SSL_CRL", TokenType::MASTER_SSL_CRL },
        { "MASTER_SSL_CRLPATH", TokenType::MASTER_SSL_CRLPATH },
        { "MASTER_SSL_KEY", TokenType::MASTER_SSL_KEY },
        { "MASTER_TLS_VERSION", TokenType::MASTER_TLS_VERSION },
        { "MASTER_USER", TokenType::MASTER_USER },
        { "MAX_CONNECTIONS_PER_HOUR", TokenType::MAX_CONNECTIONS_PER_HOUR },
        { "MAX_QUERIES_PER_HOUR", TokenType::MAX_QUERIES_PER_HOUR },
        { "MAX_ROWS", TokenType::MAX_ROWS },
        { "MAX_SIZE", TokenType::MAX_SIZE },
        { "MAX_STATEMENT_TIME", TokenType::MAX_STATEMENT_TIME },
        { "MAX_UPDATES_PER_HOUR", TokenType::MAX_UPDATES_PER_HOUR },
        { "MAX_USER_CONNECTIONS", TokenType::MAX_USER_CONNECTIONS },
        { "MEDIUM", TokenType::MEDIUM },
        { "MEMORY", TokenType::MEMORY },
        { "MERGE", TokenType::MERGE },
        { "MESSAGE_TEXT", TokenType::MESSAGE_TEXT },
        { "MICROSECOND", TokenType::MICROSECOND },
        { "MIGRATE", TokenType::MIGRATE },
        { "MINUTE", TokenType::MINUTE },
        { "MIN_ROWS", TokenType::MIN_ROWS },
        { "MODE", TokenType::MODE },
        { "MODIFY", TokenType::MODIFY },
        { "MONTH", TokenType::MONTH },
        { "MULTILINESTRING", TokenType::MULTILINESTRING },
        { "MULTIPOINT", TokenType::MULTIPOINT },
        { "MULTIPOLYGON", TokenType::MULTIPOLYGON },
        { "MUTEX", TokenType::MUTEX },
        { "MYSQL_ERRNO", TokenType::MYSQL_ERRNO },
        { "NAME", TokenType::NAME },
        { "NAMES", TokenType::NAMES },
        { "NATIONAL", TokenType::NATIONAL },
        { "NCHAR", TokenType::NCHAR },
        { "NDB", TokenType::NDB },
        { "NDBCLUSTER", TokenType::NDBCLUSTER },
        { "NEVER", TokenType::NEVER },
        { "NEW", TokenType::NEW },
        { "NEXT", TokenType::NEXT },
        { "NO", TokenType::NO },
        { "NODEGROUP", TokenType::NODEGROUP },
        { "NONBLOCKING", TokenType::NONBLOCKING },
        { "NONE", TokenType::NONE },
        { "NO_WAIT", TokenType::NO_WAIT },
        { "NUMBER", TokenType::NUMBER },
        { "NVARCHAR", TokenType::NVARCHAR },
        { "OFFSET", TokenType::OFFSET },
        { "OLD_PASSWORD", TokenType::OLD_PASSWORD },
        { "ONE", TokenType::ONE },
        { "ONLY", TokenType::ONLY },
        { "OPEN", TokenType::OPEN },
        { "OPTIONS", TokenType::OPTIONS },
        { "OWNER", TokenType::OWNER },
        { "PACK_KEYS", TokenType::PACK_KEYS },
        { "PAGE", TokenType::PAGE },
        { "PARSER", TokenType::PARSER },
        { "PARSE_GCOL_EXPR", TokenType::PARSE_GCOL_EXPR },
        { "PARTIAL", TokenType::PARTIAL },
        { "PARTITIONING", TokenType::PARTITIONING },
        { "PARTITIONS", TokenType::PARTITIONS },
        { "PASSWORD", TokenType::PASSWORD },
        { "PHASE", TokenType::PHASE },
        { "PLUGIN", TokenType::PLUGIN },
        { "PLUGINS", TokenType::PLUGINS },
        { "PLUGIN_DIR", TokenType::PLUGIN_DIR },
        { "POINT", TokenType::POINT },
        { "POLYGON", TokenType::POLYGON },
        { "PORT", TokenType::PORT },
        { "PRECEDES", TokenType::PRECEDES },
        { "PREPARE", TokenType::PREPARE },
        { "PRESERVE", TokenType::PRESERVE },
        { "PREV", TokenType::PREV },
        { "PRIVILEGES", TokenType::PRIVILEGES },
        { "PROCESSLIST", TokenType::PROCESSLIST },
        { "PROFILE", TokenType::PROFILE },
        { "PROFILES", TokenType::PROFILES },
        { "PROXY", TokenType::PROXY },
        { "QUARTER", TokenType::QUARTER },
        { "QUERY", TokenType::QUERY },
        { "QUICK", TokenType::QUICK },
        { "READ_ONLY", TokenType::READ_ONLY },
        { "REBUILD", TokenType::REBUILD },
        { "RECOVER", TokenType::RECOVER },
        { "REDOFILE", TokenType::REDOFILE },
        { "REDO_BUFFER_SIZE", TokenType::REDO_BUFFER_SIZE },
        { "REDUNDANT", TokenType::REDUNDANT },
        { "RELAY", TokenType::RELAY },
        { "RELAYLOG", TokenType::RELAYLOG },
        { "RELAY_LOG_FILE", TokenType::RELAY_LOG_FILE },
        { "RELAY_LOG_POS", TokenType::RELAY_LOG_POS },
        { "RELAY_THREAD", TokenType::RELAY_THREAD },
        { "RELOAD", TokenType::RELOAD },
        { "REMOVE", TokenType::REMOVE },
        { "REORGANIZE", TokenType::REORGANIZE },
        { "REPAIR", TokenType::REPAIR },
        { "REPEATABLE", TokenType::REPEATABLE },
        { "REPLICATE_DO_DB", TokenType::REPLICATE_DO_DB },
        { "REPLICATE_DO_TABLE", TokenType::REPLICATE_DO_TABLE },
        { "REPLICATE_IGNORE_DB", TokenType::REPLICATE_IGNORE_DB },
        { "REPLICATE_IGNORE_TABLE", TokenType::REPLICATE_IGNORE_TABLE },
        { "REPLICATE_REWRITE_DB", TokenType::REPLICATE_REWRITE_DB },
        { "REPLICATE_WILD_DO_TABLE", TokenType::REPLICATE_WILD_DO_TABLE },
        { "REPLICATE_WILD_IGNORE_TABLE", TokenType::REPLICATE_WILD_IGNORE_TABLE },
        { "REPLICATION", TokenType::REPLICATION },
        { "RESET", TokenType::RESET },
        { "RESTORE", TokenType::RESTORE },
        { "RESUME", TokenType::RESUME },
        { "RETURNED_SQLSTATE", TokenType::RETURNED_SQLSTATE },
        { "RETURNS", TokenType::RETURNS },
        { "REVERSE", TokenType::REVERSE },
        { "ROLLBACK", TokenType::ROLLBACK },
        { "ROLLUP", TokenType::ROLLUP },
        { "ROTATE", TokenType::ROTATE },
        { "ROUTINE", TokenType::ROUTINE },
        { "ROW", TokenType::ROW },
        { "ROWS", TokenType::ROWS },
        { "ROW_COUNT", TokenType::ROW_COUNT },
        { "ROW_FORMAT", TokenType::ROW_FORMAT },
        { "RTREE", TokenType::RTREE },
        { "SAVEPOINT", TokenType::SAVEPOINT },
        { "SCHEDULE", TokenType::SCHEDULE },
        { "SCHEMA_NAME", TokenType::SCHEMA_NAME },
        { "SECOND", TokenType::SECOND },
        { "SECURITY", TokenType::SECURITY },
        { "SERIAL", TokenType::SERIAL },
        { "SERIALIZABLE", TokenType::SERIALIZABLE },
        { "SERVER", TokenType::SERVER },
        { "SESSION", TokenType::SESSION },
        { "SHARE", TokenType::SHARE },
        { "SHUTDOWN", TokenType::SHUTDOWN },
        { "SIGNED", TokenType::SIGNED },
        { "SIMPLE", TokenType::SIMPLE },
        { "SLAVE", TokenType::SLAVE },
        { "SLOW", TokenType::SLOW },
        { "SNAPSHOT", TokenType::SNAPSHOT },
        { "SOCKET", TokenType::SOCKET },
        { "SOME", TokenType::SOME },
        { "SONAME", TokenType::SONAME },
        { "SOUNDS", TokenType::SOUNDS },
        { "SOURCE", TokenType::SOURCE },
        { "SQL_AFTER_GTIDS", TokenType::SQL_AFTER_GTIDS },
        { "SQL_AFTER_MTS_GAPS", TokenType::SQL_AFTER_MTS_GAPS },
        { "SQL_BEFORE_GTIDS", TokenType::SQL_BEFORE_GTIDS },
        { "SQL_BUFFER_RESULT", TokenType::SQL_BUFFER_RESULT },
        { "SQL_CACHE", TokenType::SQL_CACHE },
        { "SQL_NO_CACHE", TokenType::SQL_NO_CACHE },
        { "SQL_THREAD", TokenType::SQL_THREAD },
        { "SQL_TSI_DAY", TokenType::SQL_TSI_DAY },
        { "SQL_TSI_HOUR", TokenType::SQL_TSI_HOUR },
        { "SQL_TSI_MINUTE", TokenType::SQL_TSI_MINUTE },
        { "SQL_TSI_MONTH", TokenType::SQL_TSI_MONTH },
        { "SQL_TSI_QUARTER", TokenType::SQL_TSI_QUARTER },
        { "SQL_TSI_SECOND", TokenType::SQL_TSI_SECOND },
        { "SQL_TSI_WEEK", TokenType::SQL_TSI_WEEK },
        { "SQL_TSI_YEAR", TokenType::SQL_TSI_YEAR },
        { "STACKED", TokenType::STACKED },
        { "START", TokenType::START },
        { "STARTS", TokenType::STARTS },
        { "STATS_AUTO_RECALC", TokenType::STATS_AUTO_RECALC },
        { "STATS_PERSISTENT", TokenType::STATS_PERSISTENT },
        { "STATS_SAMPLE_PAGES", TokenType::STATS_SAMPLE_PAGES },
        { "STATUS", TokenType::STATUS },
        { "STOP", TokenType::STOP },
        { "STORAGE", TokenType::STORAGE },
        { "STRING", TokenType::STRING },
        { "SUBCLASS_ORIGIN", TokenType::SUBCLASS_ORIGIN },
        { "SUBJECT", TokenType::SUBJECT },
        { "SUBPARTITION", TokenType::SUBPARTITION },
        { "SUBPARTITIONS", TokenType::SUBPARTITIONS },
        { "SUPER", TokenType::SUPER },
        { "SUSPEND", TokenType::SUSPEND },
        { "SWAPS", TokenType::SWAPS },
        { "SWITCHES", TokenType::SWITCHES },
        { "TABLES", TokenType::TABLES },
        { "TABLESPACE", TokenType::TABLESPACE },
        { "TABLE_CHECKSUM", TokenType::TABLE_CHECKSUM },
        { "TABLE_NAME", TokenType::TABLE_NAME },
        { "TEMPORARY", TokenType::TEMPORARY },
        { "TEMPTABLE", TokenType::TEMPTABLE },
        { "TEXT", TokenType::TEXT },
        { "THAN", TokenType::THAN },
        { "TIME", TokenType::TIME },
        { "TIMESTAMP", TokenType::TIMESTAMP },
        { "TIMESTAMPADD", TokenType::TIMESTAMPADD },
        { "TIMESTAMPDIFF", TokenType::TIMESTAMPDIFF },
        { "TRANSACTION", TokenType::TRANSACTION },
        { "TRIGGERS", TokenType::TRIGGERS },
        { "TRUNCATE", TokenType::TRUNCATE },
        { "TYPE", TokenType::TYPE },
        { "TYPES", TokenType::TYPES },
        { "UNCOMMITTED", TokenType::UNCOMMITTED },
        { "UNDEFINED", TokenType::UNDEFINED },
        { "UNDOFILE", TokenType::UNDOFILE },
        { "UNDO_BUFFER_SIZE", TokenType::UNDO_BUFFER_SIZE },
        { "UNICODE", TokenType::UNICODE },
        { "UNINSTALL", TokenType::UNINSTALL },
        { "UNKNOWN", TokenType::UNKNOWN },
        { "UNTIL", TokenType::UNTIL },
        { "UPGRADE", TokenType::UPGRADE },
        { "USER", TokenType::USER },
        { "USER_RESOURCES", TokenType::USER_RESOURCES },
        { "USE_FRM", TokenType::USE_FRM },
        { "VALIDATION", TokenType::VALIDATION },
        { "VALUE", TokenType::VALUE },
        { "VARIABLES", TokenType::VARIABLES },
        { "VIEW", TokenType::VIEW },
        { "WAIT", TokenType::WAIT },
        { "WARNINGS", TokenType::WARNINGS },
        { "WEEK", TokenType::WEEK },
        { "WEIGHT_STRING", TokenType::WEIGHT_STRING },
        { "WITHOUT", TokenType::WITHOUT },
        { "WORK", TokenType::WORK },
        { "WRAPPER", TokenType::WRAPPER },
        { "X509", TokenType::X509 },
        { "XA", TokenType::XA },
        { "XID", TokenType::XID },
        { "XML", TokenType::XML },
        { "YEAR", TokenType::YEAR }
    };
}
#endif
